### ISSUE TITLE
book 结构体中添加 gorm.Model

### ISSUE THREAD

**Issue by 624464641** [weenxin/ulitmate_go_notebook_reading#1]
type Book struct {
	gorm.Model
	Id     int64  `json:"id,omitempty"`
	Title  string `json:"title,omitempty" json:"title,omitempty"`
	Author string `json:"author,omitempty" json:"author,omitempty"`
	Pages  int32  `json:"pages" json:"pages,omitempty"`
	Weight int32  `json:"weight,omitempty" json:"weight,omitempty"` // 存储时使用g
}

result := sqlmock.NewResult(1, 1)
		mock.MatchExpectationsInOrder(false)
		mock.ExpectBegin()
		mock.ExpectExec("^INSERT INTO `books` ").
			WithArgs(b.Title, b.Author, b.Pages, b.Weight, AnyTime{}, AnyTime{}, nil).
			WillReturnResult(result)
		mock.ExpectCommit()

添加了model后  总是提示call to ExecQuery

**Comment by weenxin** [comment]
@624464641 更改了下代码，可以看下是否能满足你的需求？

**Comment by weenxin** [comment]
@624464641 还有啥问题吗？ 如果没有问题，我就close掉了哈。

**Comment by weenxin** [comment]
@624464641 有问题可以在reopen
